### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by tokorokot** [tokorokot/PVPSound#1]
#to do list
- [x] Addon messages prefix fix (new namspace of func C_ChatInfo)
- [x] Remade slash commands options
- [ ] reaplace events:
 - WORLD_MAP_UPDATE
 - UPDATE_WORLD_STATES
 - WORLD_STATES_UI_TIMER_UPDATE
     At the moment they are just commented
     The best candidates for replace are AREA_POIS_UPDATED and UPDATE_ALL_UI_WIDGETS

- [ ] remove STand of ancients BG
- [ ] add seethering shore BG
- [ ] update for classic
- [ ] change interactions with map and its Landmarks
       There is no landmarks func anymore. We should use POI API. in namespace C_AreaPOIInfo. Get AreaPOIForMap and GetAreaPOIInfo
- [ ] change zones id due to New "getId" system 
- [x] change localization file (bg messages have changed)
