### ISSUE TITLE
ToDo List 2

### ISSUE THREAD

**Issue by tokorokot** [tokorokot/PVPSound#2]
- [x] Fix killing blow sounds
- [x] Fix Warsong Gulch
- [x] Fix Twin Peaks
- [x] Fix Arathi Basin
- [x] Fix The Battle for Gilneas
- [x] Fix Isle of Conquest
- [x] Fix Alterac Valley
- [x] Fix Eye of the Storm
- [x] Fix Temlpe of Kotmogu
- [x] Fix Silvershard Mines
- [x] Fix Deepwind Gorge
- [x] Fix Tol Barad
- [x] Fix Wintergrasp
- [x] Fix arenas
- [x] Remove Strand of the Ancients
- [x] Add Seethering shore
- [ ] Find out IDs for bases "in conflict" in EOTS
- [ ] ToK is BG_MESSAGE driven at the moment, make it WIDGET driven and add "dominating" sounds
- [x] Replace BG_message to PVP_MATCH_COMPLETED event for end of match sounds
- [x] Add time remaining anouncements in WSG, TP , Arenas...
- [x] Update brawls routines
- [x] Update for classic
- [ ] Check En client stability
